const estructura_analysis_preparation= {
    entity:'analysis_preparation',
    attributes:{
        id_analysis_preparation:{
            html:{
                tag:'input',
                type:'number',
                component_visible_size:5
            },
            db:{
                is_pk:true,
                is_autoincrement:true,
                type:'int'
            },
            rules:{
                validations: {
                    ADD: {
                        min_size: 1,
                        max_size: 11,
                        exp_reg: '^[0-9]+$'
                    },
                    EDIT: {
                        min_size: 1,
                        max_size: 11,
                        exp_reg: '^[0-9]+$'
                    },
                    SEARCH: {
                        max_size: 11,
                        exp_reg: '^[0-9]+$'
                    }
                }
            }
        },
        name_analysis_preparation:{
            html:{
                tag:'input',
                type:'text',
                component_visible_size:20
            },
            db:{
                is_pk:false,
                is_autoincrement:false,
                type:'string'
            },
            rules:{
                validations:{
                    ADD:{
                        min_size:8,
                        max_size:100,
                        exp_reg:'^[A-Za-z\\s]+$'
                    },
                    EDIT:{
                        min_size:8,
                        max_size:100,
                        exp_reg:'^[A-Za-z\\s]+$'
                    },
                    SEARCH:{
                        max_size:100,
                        exp_reg:'^[A-Za-z\\s]+$'
                    }
                }
            }
        },
        description_analysis_preparation:{
            html:{
                tag:'textarea',
                rows:5,
                columns:40,
                component_visible_size:200
            },
            db:{
                is_pk:false,
                is_autoincrement:false,
                type:'string'
            },
            rules:{
                validations:{
                    ADD:{
                        min_size:80,
                        max_size:5000,
                        exp_reg:'^[A-Za-z\\s]+$'
                    },
                    EDIT:{
                        min_size:80,
                        max_size:5000,
                        exp_reg:'^[A-Za-z\\s]+$'
                    },
                    SEARCH:{
                        max_size:5000,
                        exp_reg:'^[A-Za-z\\s]+$'
                    }
                }
            }
        },
        bib_analysis_preparation:{
            html:{
                tag:'textarea',
                rows:5,
                columns:40,
                component_visible_size:200
            },
            db:{
                is_pk:false,
                is_autoincrement:false,
                type:'string'
            },
            rules:{
                validations:{
                    ADD:{
                        min_size:16,
                        max_size:200,
                        exp_reg:'^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s\\.,:;]+$'
                    },
                    EDIT:{
                        min_size:16,
                        max_size:200,
                        exp_reg:'^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s\\.,:;]+$'
                    },
                    SEARCH:{
                        max_size:200,
                        exp_reg:'^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s\\.,:;]+$'
                    }
                }
            }
        },
        //add y edit
        nuevo_file_analysis_preparation:{
            html:{
                tag:'input',
                type:'file',
                component_visible_size:20
            },
            db:{
                is_pk:false,
                is_autoincrement:false,
                type:'string'
            },
            rules:{
                validations:{
                    ADD:{
                        not_exist_file:true,
                        type_file:['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
                        max_size_file:2000000,
                        min_file_name_size:7,
                        max_file_name_size:100,
                        format_name_file:'^[A-Za-z\\._-]+$'
                    },
                    EDIT:{
                        type_file:['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
                        max_size_file:2000000,
                        min_file_name_size:7,
                        max_file_name_size:100,
                        format_name_file:'^[A-Za-z\\._-]+$'
                    }
                }
            }
        },
        //search
        file_analysis_preparation:{
            html:{
                tag:'input',
                type:'text',
                component_visible_size:20
            },
            db:{
                is_pk:false,
                is_autoincrement:false,
                type:'string'
            },
            rules:{
                validations:{
                    SEARCH:{
                        max_size:100,
                        exp_reg:'^[A-Za-z\\.]+$'
                    }
                }
            }
        }
    }
}