let persona_def_tests = [
    // campos no ficheros
    ['persona','nombre_persona',1,'cumple tamaño minimo','ADD','nombre_persona_min_size_KO','Tamaño muy corto. Debe estar entre 4 y 20 caracteres'],
    ['persona','nombre_persona',2,'cumple tamaño maximo','ADD','nombre_persona_max_size_KO','Tamaño muy grande. Debe estar entre 4 y 20 caracteres'],
    ['persona','nombre_persona',3,'cumple formato','ADD','nombre_persona_format_KO','Formato inválido. Debe ser alfabético'],
    ['persona','nombre_persona',4,'es correcto','ADD',true,'Nombre persona correcto'],
    ['persona','nombre_persona',5,'cumple tamaño minimo','EDIT','nombre_persona_min_size_KO','Tamaño muy corto. Debe estar entre 4 y 20 caracteres'],
    ['persona','nombre_persona',6,'cumple tamaño maximo','EDIT','nombre_persona_max_size_KO','Tamaño muy grande. Debe estar entre 4 y 20 caracteres'],
    ['persona','nombre_persona',7,'cumple formato','EDIT','nombre_persona_format_KO','Formato inválido. Debe ser alfabético'],
    ['persona','nombre_persona',8,'es correcto','EDIT',true,'Nombre persona correcto'],

    ['persona','apellidos_persona',9,'cumple tamaño minimo','ADD','apellidos_persona_min_size_KO','Tamaño muy corto. Debe estar entre 6 y 20 caracteres'],
    ['persona','apellidos_persona',10,'cumple tamaño maximo','ADD','apellidos_persona_max_size_KO','Tamaño muy grande. Debe estar entre 6 y 20 caracteres'],
    ['persona','apellidos_persona',11,'cumple formato','ADD','apellidos_persona_format_KO','Formato inválido. Debe ser alfabético'],
    ['persona','apellidos_persona',12,'es correcto','ADD',true,'Apellidos correctos'],
    ['persona','apellidos_persona',13,'cumple tamaño minimo','EDIT','apellidos_persona_min_size_KO','Tamaño muy corto. Debe estar entre 6 y 20 caracteres'],
    ['persona','apellidos_persona',14,'cumple tamaño maximo','EDIT','apellidos_persona_max_size_KO','Tamaño muy grande. Debe estar entre 6 y 20 caracteres'],
    ['persona','apellidos_persona',15,'cumple formato','EDIT','apellidos_persona_format_KO','Formato inválido. Debe ser alfabético'],
    ['persona','apellidos_persona',16,'es correcto','EDIT',true,'Apellidos correctos'],

    ['persona','fechaNacimiento_persona',17,'cumple tamaño minimo','ADD','fechaNacimiento_persona_min_size_KO','Tamaño muy corto. Debe tener al menos 6 caracteres'],
    ['persona','fechaNacimiento_persona',18,'cumple tamaño maximo','ADD','fechaNacimiento_persona_max_size_KO','Tamaño muy largo. Máximo 10 caracteres'],
    ['persona','fechaNacimiento_persona',19,'cumple formato','ADD','fechaNacimiento_persona_format_KO','Formato no válido. Debe ser DD/MM/AAAA'],
    ['persona','fechaNacimiento_persona',20,'es correcto','ADD',true,'Fecha de nacimiento correcta'],
    ['persona','fechaNacimiento_persona',21,'cumple tamaño minimo','EDIT','fechaNacimiento_persona_min_size_KO','Tamaño muy corto. Debe tener al menos 6 caracteres'],
    ['persona','fechaNacimiento_persona',22,'cumple tamaño maximo','EDIT','fechaNacimiento_persona_max_size_KO','Tamaño muy largo. Máximo 10 caracteres'],
    ['persona','fechaNacimiento_persona',23,'cumple formato','EDIT','fechaNacimiento_persona_format_KO','Formato no válido. Debe ser DD/MM/AAAA'],
    ['persona','fechaNacimiento_persona',24,'es correcto','EDIT',true,'Fecha de nacimiento correcta'],

    ['persona','telefono_persona',25,'cumple tamaño minimo','ADD','telefono_persona_min_size_KO','Tamaño muy corto. Debe tener 9 caracteres'],
    ['persona','telefono_persona',26,'cumple tamaño maximo','ADD','telefono_persona_max_size_KO','Tamaño muy largo. Debe tener 9 caracteres'],
    ['persona','telefono_persona',27,'cumple formato','ADD','telefono_persona_format_KO','Formato inválido. Debe ser numérico'],
    ['persona','telefono_persona',28,'es correcto','ADD',true,'Teléfono correcto'],
    ['persona','telefono_persona',29,'cumple tamaño minimo','EDIT','telefono_persona_min_size_KO','Tamaño muy corto. Debe tener 9 caracteres'],
    ['persona','telefono_persona',30,'cumple tamaño maximo','EDIT','telefono_persona_max_size_KO','Tamaño muy largo. Debe tener 9 caracteres'],
    ['persona','telefono_persona',31,'cumple formato','EDIT','telefono_persona_format_KO','Formato inválido. Debe ser numérico'],
    ['persona','telefono_persona',32,'es correcto','EDIT',true,'Teléfono correcto'],

    ['persona', 'email_persona', 33, 'cumple tamaño minimo', 'ADD', 'email_persona_min_size_KO', 'Tamaño muy corto, Deberia estar entre 5 y 100 caracteres'],
    ['persona', 'email_persona', 34, 'cumple tamaño maximo', 'ADD', 'email_persona_max_size_KO', 'Tamaño muy grande. Deberia estar entre 5 y 100 caracteres'],
    ['persona', 'email_persona', 35, 'cumple formato', 'ADD', 'email_persona_format_KO', 'Formato invalido, deberia ser del tipo usuario@dominio.xx'],
    ['persona', 'email_persona', 36, 'es correcto', 'ADD', true, 'Email correcto'],
    ['persona', 'email_persona', 37, 'cumple tamaño minimo', 'EDIT', 'email_persona_min_size_KO', 'Tamaño muy corto, Deberia estar entre 5 y 100 caracteres'],
    ['persona', 'email_persona', 38, 'cumple tamaño minimo', 'EDIT', 'email_persona_max_size_KO', 'Tamaño muy grande, Deberia estar entre 5 y 100 caracteres'],
    ['persona', 'email_persona', 39, 'cumple formato', 'EDIT', 'email_persona_format_KO', 'Formato invalido, deberia ser del tipo usuario@dominio.xx'],
    ['persona', 'email_persona', 40, 'es correcto', 'EDIT', true, 'Email correcto'],

    // campos fichero
    ['persona','nuevo_foto_persona',41,'existe fichero','ADD','nuevo_foto_persona_not_exist_file_KO','El fichero no existe'],
    ['persona','nuevo_foto_persona',42,'cumple nombre fichero','ADD','nuevo_foto_persona_format_name_file_KO','Nombre de fichero inválido'],
    ['persona','nuevo_foto_persona',43,'cumple tipo fichero','ADD','nuevo_foto_persona_type_file_KO','Tipo de fichero no permitido'],
    ['persona','nuevo_foto_persona',44,'cumple tamaño maximo fichero','ADD','nuevo_foto_persona_max_size_file_KO','Tamaño de fichero demasiado grande'],
    ['persona','nuevo_foto_persona',45,'cumple tamaño mínimo nombre fichero','ADD','nuevo_foto_persona_min_size_name_KO','Nombre de fichero demasiado corto'],
    ['persona','nuevo_foto_persona',46,'cumple tamaño máximo nombre fichero','ADD','nuevo_foto_persona_max_size_name_KO','Nombre de fichero demasiado largo'],
    ['persona','nuevo_foto_persona',47,'fichero ok','ADD',true,'Fichero correcto'],
    ['persona','nuevo_foto_persona',48,'no existe fichero','EDIT',true,'Fichero correcto'],
    ['persona','nuevo_foto_persona',49,'cumple nombre fichero','EDIT','nuevo_foto_persona_format_name_file_KO','Nombre de fichero inválido'],
    ['persona','nuevo_foto_persona',50,'cumple tipo fichero','EDIT','nuevo_foto_persona_type_file_KO','Tipo de fichero no permitido'],
    ['persona','nuevo_foto_persona',51,'cumple tamaño maximo fichero','EDIT','nuevo_foto_persona_max_size_file_KO','Tamaño de fichero demasiado grande'],
    ['persona','nuevo_foto_persona',52,'cumple tamaño minimo nombre fichero','EDIT','nuevo_foto_persona_min_size_name_KO','Nombre de fichero demasiado corto'],
    ['persona','nuevo_foto_persona',53,'cumple tamaño maximo nombre fichero','EDIT','nuevo_foto_persona_max_size_name_KO','Nombre de fichero demasiado largo'],
    ['persona','nuevo_foto_persona',54,'fichero ok','EDIT',true,'Fichero correcto'],
];

let persona_tests_fields = Array(
    ['persona','nombre_persona',1,1,'ADD',[{nombre_persona:'aa'}],'nombre_persona_min_size_KO'],
    ['persona','nombre_persona',2,2,'ADD',[{nombre_persona:'a'.repeat(20)}],'nombre_persona_max_size_KO'],
    ['persona','nombre_persona',3,3,'ADD',[{nombre_persona:'aaaaaa1'}],'nombre_persona_format_KO'],
    ['persona','nombre_persona',4,4,'ADD',[{nombre_persona:'javi'}],true],
    ['persona','nombre_persona',5,5,'EDIT',[{nombre_persona:'aa'}],'nombre_persona_min_size_KO'],
    ['persona','nombre_persona',6,6,'EDIT',[{nombre_persona:'aaaaaaaaaaaaaaaaaaaaa'}],'nombre_persona_max_size_KO'],
    ['persona','nombre_persona',7,7,'EDIT',[{nombre_persona:'aaaaaa1'}],'nombre_persona_format_KO'],
    ['persona','nombre_persona',8,8,'EDIT',[{nombre_persona:'javi'}],true],

    ['persona', 'apellidos_persona', 9, 9, 'ADD', [{apellidos_persona:'aaa'}], 'apellidos_persona_min_size_KO'],
    ['persona', 'apellidos_persona', 10, 10, 'ADD', [{apellidos_persona:'a'.repeat(20)}], 'apellidos_persona_max_size_KO'],
    ['persona', 'apellidos_persona', 11, 11, 'ADD', [{apellidos_persona:'aaaaa1'}], 'apellidos_persona_format_KO'],
    ['persona', 'apellidos_persona', 12, 12, 'ADD', [{apellidos_persona:'perez perez'}], true],
    ['persona', 'apellidos_persona', 13, 13, 'EDIT', [{apellidos_persona:'aaa'}], 'apellidos_persona_min_size_KO'],
    ['persona', 'apellidos_persona', 14, 14, 'EDIT', [{apellidos_persona:'a'.repeat(20)}], 'apellidos_persona_max_size_KO'],
    ['persona', 'apellidos_persona', 15, 15, 'EDIT', [{apellidos_persona:'aaaaa1'}], 'apellidos_persona_format_KO'],
    ['persona', 'apellidos_persona', 16, 16, 'EDIT', [{apellidos_persona:'perez perez'}], true],

    ['persona', 'fechaNacimiento_persona', 17, 17, 'ADD', [{fechaNacimiento_persona:'1/2/3'}], 'fechaNacimiento_persona_min_size_KO'],
    ['persona', 'fechaNacimiento_persona', 18, 18, 'ADD', [{fechaNacimiento_persona:'01/02/20030'}], 'fechaNacimiento_persona_max_size_KO'],
    ['persona', 'fechaNacimiento_persona', 19, 19, 'ADD', [{fechaNacimiento_persona:'ab/02/2003'}], 'fechaNacimiento_persona_format_KO'],
    ['persona', 'fechaNacimiento_persona', 20, 20, 'ADD', [{fechaNacimiento_persona:'01/02/2003'}], true],
    ['persona', 'fechaNacimiento_persona', 21, 21, 'EDIT', [{fechaNacimiento_persona:'1/2/3'}], 'fechaNacimiento_persona_min_size_KO'],
    ['persona', 'fechaNacimiento_persona', 22, 22, 'EDIT', [{fechaNacimiento_persona:'01/02/20030'}], 'fechaNacimiento_persona_max_size_KO'],
    ['persona', 'fechaNacimiento_persona', 23, 23, 'EDIT', [{fechaNacimiento_persona:'0ab/02/2003'}], 'fechaNacimiento_persona_format_KO'],
    ['persona', 'fechaNacimiento_persona', 24, 24, 'EDIT', [{fechaNacimiento_persona:'01/02/2003'}], true],

    ['persona', 'telefono_persona', 25, 25, 'ADD', [{telefono_persona:'12345678'}], 'telefono_persona_min_size_KO'],
    ['persona', 'telefono_persona', 26, 26, 'ADD', [{telefono_persona:'1234567890'}], 'telefono_persona_max_size_KO'],
    ['persona', 'telefono_persona', 27, 27, 'ADD', [{telefono_persona:'a23456789'}], 'telefono_persona_format_KO'],
    ['persona', 'telefono_persona', 28, 28, 'ADD', [{telefono_persona:'123456789'}], true],
    ['persona', 'telefono_persona', 29, 29, 'EDIT', [{telefono_persona:'12345678'}], 'telefono_persona_min_size_KO'],
    ['persona', 'telefono_persona', 30, 30, 'EDIT', [{telefono_persona:'1234567890'}], 'telefono_persona_max_size_KO'],
    ['persona', 'telefono_persona', 31, 31, 'EDIT', [{telefono_persona:'a23456789'}], 'telefono_persona_format_KO'],
    ['persona', 'telefono_persona', 32, 32, 'EDIT', [{telefono_persona:'123456789'}], true],

    ['persona', 'email_persona', 33, 33, 'ADD', [{email_persona:'aaaa'}], 'email_persona_min_size_KO'],
    ['persona', 'email_persona', 34, 34, 'ADD', [{email_persona:'a'.repeat(100)}], 'email_persona_max_size_KO'],
    ['persona', 'email_persona', 35, 35, 'ADD', [{email_persona:''}], 'email_persona_format_KO'],
    ['persona', 'email_persona', 36, 36, 'ADD', [{email_persona:'ejemplo@gmail.com'}], true ],
    ['persona', 'email_persona', 37, 37, 'EDIT', [{email_persona:'aaaa'}], 'email_persona_min_size_KO'],
    ['persona', 'email_persona', 38, 38, 'EDIT', [{email_persona:'a'.repeat(100)}], 'email_persona_max_size_KO'],
    ['persona', 'email_persona', 39, 39, 'EDIT', [{email_persona:''}], 'email_persona_format_KO'],
    ['persona', 'email_persona', 40, 40, 'EDIT', [{email_persona:'ejemplo@gmail.com'}],true],
);

let persona_tests_files = Array(
   Array('persona','nuevo_foto_persona',11,5,'ADD','existe',[],'nuevo_foto_persona_not_exist_file_KO'),
 /*   Array('persona','nuevo_foto_persona',6,6,'ADD','cumple nombre fichero',Array('1111','image/jpeg',20000),'nuevo_foto_persona_format_name_file_KO'),
    Array('persona','nuevo_foto_persona',7,6,'ADD','type_file',Array('nombrejpg','img/pdf',20000),'nuevo_foto_persona_type_file_KO'),
 */   ['persona','nuevo_foto_persona',14,8,'ADD','max_size_name',Array({format_name_file:'nombrejpg.jpg'},{type_file:'image/jpeg'},{max_size_file:2000000000}),'nuevo_foto_persona_max_size_file_KO'],
 Array('persona','nuevo_foto_persona',17,9,'ADD','empty_file',Array({format_name_file:'nombrejpg.jpg'},{type_file:'image/jpeg'},{max_size_file:200}),true),
 /*   Array('persona','nuevo_foto_persona',9,9,'ADD','min_size_name',Array('g','image/jpeg',20000),'nuevo_foto_persona_min_size_name_KO'),
    Array('persona','nuevo_foto_persona',10,10,'ADD','max_size_name',Array('a'.repeat(101),'image/jpeg',20000),'nuevo_foto_persona_max_size_name_KO'),
    Array('persona','nuevo_foto_persona',11,11,'ADD','fichero ok',Array('nombrejpg','image/jpeg',20000),true),
    Array('persona','nuevo_foto_persona',12,12,'EDIT','noexiste',Array(),true),
    Array('persona','nuevo_foto_persona',13,13,'EDIT','cumple nombre fichero',Array('1111','image/jpeg',20000),'nuevo_foto_persona_format_name_file_KO'),
    Array('persona','nuevo_foto_persona',14,14,'EDIT','type_file',Array('nombrejpg','img/pdf',20000),'nuevo_foto_persona_type_file_KO'),
    Array('persona','nuevo_foto_persona',15,15,'EDIT','max_size_file',Array('nombrejpg','image/jpeg',200000000),'nuevo_foto_persona_max_size_file_KO'),
    Array('persona','nuevo_foto_persona',16,16,'EDIT','min_size_name',Array('g','image/jpeg',20000),'nuevo_foto_persona_min_size_name_KO'),
    Array('persona','nuevo_foto_persona',17,17,'EDIT','max_size_name',Array('a'.repeat(101),'image/jpeg',20000),'nuevo_foto_persona_max_size_name_KO'),
    Array('persona','nuevo_foto_persona',18,18,'EDIT','fichero ok',Array('nombrejpg','image/jpeg',20000),true),
  */ 
);