var textos_ES={
    //textos titulos
    'text_titulo_app': 'Interfaz ET2 IU',
    'text_titulo_menu': 'Opciones menu',
    'text_titulo_pie': 'Pie de página',
    'label_seleccioncolumnas': 'Seleccionar columnas',
    //textos tests

    //textos menu
    'text_menu_alumnograduacion': 'Gestionar alumno',
    //alumnograduacion
    'text_titulo_page_alumnograduacion': 'Gestion de datos personales',
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Dar de alta a un alumno',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Editar datos del alumno',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Eliminar datos del alumno',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Mostrar datos del alumno',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Formulario de busqueda',
    //articulo
    'text_titulo_page_articulo': 'Gestion de articulos',
    'text_contenido_titulo_form_articulo_ADD': 'Añadir un nuevo articulo',
    'text_contenido_titulo_form_articulo_EDIT': 'Editar datos de un articulo',
    'text_contenido_titulo_form_articulo_DELETE': 'Eliminar articulo',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Mostrar datos de un articulo',
    'text_contenido_titulo_form_articulo_SEARCH': 'Formulario de busqueda',
    //ubicacion
    'text_titulo_page_ubicacion': 'Gestion de ubicaciones',
    'text_contenido_titulo_form_ubicacion_ADD': 'Añadir nueva ubicacion',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Editar ubicacion',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Eliminar ubicacion',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Mostrar ubicacion',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Formulario de busqueda',
    //atributos
    'alumnograduacion_login': 'Usuario',
    'alumnograduacion_password': 'Contraseña',
    'alumnograduacion_nombre': 'Nombre',
    'alumnograduacion_apellidos': 'Apellidos',
    'alumnograduacion_titulacion': 'Titulacion',
    'alumnograduacion_dni': 'DNI',
    'alumnograduacion_telefono': 'Número de telefono',
    'alumnograduacion_direccion': 'Direccion',
    'alumnograduacion_email': 'Correo electronico',
    'nuevo_alumnograduacion_fotoacto': 'Nueva foto',
    'alumnograduacion_fotoacto': 'Foto',

    'CodigoA': 'Código artículo',
    'AutoresA': 'Nombres autores',
    'TituloA': 'Titulo artículo',
    'TituloR': 'Titulo revista',
    'ISSN': 'ISSN',
    'VolumenR': 'Volumen de la revista',
    'PagIniA': 'Numero página inicial artículo',
    'PagFinA': 'Numero página final artículo',
    'FechaPublicacionR': 'Fecha publicación artículo',
    'FicheropdfA': 'Fichero artículo',
    'nuevo_FicheropdfA': 'Nuevo fichero artículo',
    'EstadoA': 'Estado de tramitación del articulo',

    'id_site': 'Identificador sitio',
    'site_latitud': 'Latitud WGS84',
    'site_longitud': 'Longitud WGS84',
    'site_altitude': 'Altitud sitio',
    'site_locality': 'Localidad del sitio',
    'site_provider_login': 'Login proveedor sitio',
    'site_north_photo': 'Foto hacia el norte',
    'site_south_photo': 'Foto hacia el sur',
    'site_east_photo': 'Foto hacia el este',
    'site_west_photo': 'Foto hacia el oeste',
    'nuevo_site_north_photo': 'Nueva foto hacia el norte',
    'nuevo_site_south_photo': 'Nueva foto hacia el sur',
    'nuevo_site_east_photo': 'Nueva foto hacia el este',
    'nuevo_site_west_photo': 'Nueva foto hacia el oeste',
    //labels
    'label_alumnograduacion_login': 'Usuario',
    'label_alumnograduacion_password': 'Contraseña',
    'label_alumnograduacion_nombre': 'Nombre',
    'label_alumnograduacion_apellidos': 'Apellidos',
    'label_alumnograduacion_titulacion': 'Titulacion',
    'label_alumnograduacion_dni': 'DNI',
    'label_alumnograduacion_telefono': 'Número de telefono',
    'label_alumnograduacion_direccion': 'Direccion',
    'label_alumnograduacion_email': 'Correo electronico',
    'label_nuevo_alumnograduacion_fotoacto': 'Nueva foto',
    'label_alumnograduacion_fotoacto': 'Foto',

    'label_CodigoA': 'Código artículo',
    'label_AutoresA': 'Nombres autores',
    'label_TituloA': 'Titulo artículo',
    'label_TituloR': 'Titulo revista',
    'label_ISSN': 'ISSN',
    'label_VolumenR': 'Volumen de la revista',
    'label_PagIniA': 'Pagina inicial artículo',
    'label_PagFinA': 'Pagina final artículo',
    'label_FechaPublicacionR': 'Fecha publicacion artículo',
    'label_FicheropdfA': 'Fichero articulo',
    'label_nuevo_FicheropdfA': 'Nuevo fichero articulo',
    'label_EstadoA': 'Estado de tramitación del artículo',

    'label_id_site': 'Identificador sitio',
    'label_site_latitud': 'Latitud WGS84',
    'label_site_longitud': 'Longitud WGS84',
    'label_site_altitude': 'Altitud sitio',
    'label_site_locality': 'Localidad del sitio',
    'label_site_provider_login': 'Logon proveedor sitio',
    'label_site_north_photo': 'Foto hacia el norte',
    'label_site_south_photo': 'Foto hacia el sur',
    'label_site_east_photo': 'Foto hacia el este',
    'label_site_west_photo': 'Foto hacia el oeste',
    'label_nuevo_site_north_photo': 'Nueva foto hacia el norte',
    'label_nuevo_site_south_photo': 'Nueva foto hacia el sur',
    'label_nuevo_site_east_photo': 'Nueva foto hacia el este',
    'label_nuevo_site_west_photo': 'Nueva foto hacia el oeste',
    //errores validaciones
    ////alumnograduacion_login
    'alumnograduacion_login_min_size_KO': 'El login es demasiado corto, deberia tener entre 4 y 15 caracteres',
    'alumnograduacion_login_max_size_KO': 'El login es demasiado largo, deberia tener entre 4 y 15 caracteres',
    'alumnograduacion_login_format_KO': 'El login solo acepta caracteres alfabeticos sin acentos ni ñ',
    //alumnograduacion_password
    'alumnograduacion_password_min_size_KO': 'La contraseña es demasiado corta, debería tener entre 8 y 64 caracteres',
    'alumnograduacion_password_max_size_KO': 'La contraseña es demasiado larga, debería tener entre 8 y 64 caracteres',
    'alumnograduacion_password_format_KO': 'La contraseña incumple el formato requerido, solo se aceptan caracteres alfabeticos sin acentos, ni ñ, y espacios',
    //alumnograduacion_nombre
    'alumnograduacion_nombre_min_size_KO': 'El nombre es demasiado corto, deberia tener entre 2 y 25 caracteres',
    'alumnograduacion_nombre_max_size_KO': 'El nombre es demasiado largo, deberia tener entre 2 y 25 caracteres',
    'alumnograduacion_nombre_format_KO': 'Error, solo se aceptan caracteres alfabeticos, ñ y acentos incluidos',
    //alumnograduacion_apellidos
    'alumnograduacion_apellidos_min_size_KO': 'Los apellidos son demasiado cortos, debe tener entre 2 y 35 caracteres',
    'alumnograduacion_apellidos_max_size_KO': 'Los apellidos son demasiado largos, debe tener entre 2 y 35 caracteres',
    'alumnograduacion_apellidos_format_KO': 'Error, solo se aceptan caracteres alfabeticos, ñ y acentos incluidos',
    //alumnograduacion_titulacion
    'alumnograduacion_titulacion_vacio_KO': 'Error, la titulacion no puede quedar vacia',
    'alumnograduacion_titulacion_valor_KO': 'Titulacion invalida. Solo tenemos GREI, GRIA, MEI, MIA o PCEO',
    'alumnograduacion_titulacion_max_size_KO': 'Error, valor demasiado grande. No se pueden exceder los 4 caracteres',
    'alumnograduacion_titulacion_format_KO': 'Formato incorrecto, solo se pueden meter caracteres alfabeticos en mayusculas',
    //alumnograduacion_dni
    'alumnograduacion_dni_min_size_KO': 'El dni/nie es demasiado corto. Debe tener 9 caracteres',
    'alumnograduacion_dni_max_size_KO': 'El dni/nie es demasiado largo. Debe tener 9 caracteres',
    'alumnograduacion_dni_format_KO': 'Error, la cadena introducida no es valida. El formato debe ser 12345678X(para nif) o x1234567x(para nie)',
    'alumnograduacion_dni_format_nif_KO': 'Error, la cadena introducida no es valida, la letra no se corresponde para esa combinacion de numeros',
    'alumnograduacion_dni_format_nie_KO': 'Error, la cadena introducida no es valida, la letra no se corresponde para esa combinacion de numeros',
    //alumnograduacion_telefono
    'alumnograduacion_telefono_min_size_KO': 'Los numeros de telefono no pueden tener menos de 9 caracteres',
    'alumnograduacion_telefono_max_size_KO': 'Los numeros de telefono no pueden tener mas de 9 caracteres',
    'alumnograduacion_telefono_format_KO': 'Error, solo se aceptan valores de tipo numerico',
    //alumnograduacion_direccion
    'alumnograduacion_direccion_min_size_KO': 'Error, la direccion es demasiado corta.',
    'alumnograduacion_direccion_max_size_KO': 'Error, la direccion es demasiado larga.',
    'alumnograduacion_direccion_format_KO': 'Error, solo se pueden introducir caracteres alfanuméricos, acentos y ñ incluidos, y espacios. Ademas debe seguir el formato Calle (nombre de la calle), portal, piso, codigo postal, ciudad.',
    //alumnograduacion_email
    'alumnograduacion_email_min_size_KO': 'Error, el email es demasiado corto.',
    'alumnograduacion_email_max_size_KO': 'Error, el email es demasiado largo.',
    'alumnograduacion_email_format_KO': 'El email introducido no cumple el formato valido (usuario@dominio.extension).',
    //alumnograduacion_fotoacto
    'alumnograduacion_fotoacto_max_size_KO': 'El nombre del archivo no puede tener mas de 40 caracteres',
    'alumnograduacion_fotoacto_format_KO': 'El fomato no es valido, solo se pueden meter alfabeticos sin acentos, ni ñ, ni espacios',
    //alumnograduacion_nuevo_fotoacto
    'nuevo_alumnograduacion_fotoacto_not_exist_file_KO': 'Error, si vas a subir una foto debe haber un fichero subido.',
    'nuevo_alumnograduacion_fotoacto_max_size_file_KO': 'El archivo no puede tener mas de 20MB',
    'nuevo_alumnograduacion_fotoacto_type_file_KO': 'El tipo de archivo no es valido, solo puedes meter jpg',
    'nuevo_alumnograduacion_fotoacto_format_name_file_KO': 'El nombre no es valido, solo se aceptan caracteres alfanumericos, sin ñ acentos ni espacios.',
    'nuevo_alumnograduacion_fotoacto_min_file_name_size_KO': 'Error, el nombre no puede tener menos de 7 caracteres.',
    'nuevo_alumnograduacion_fotoacto_max_file_name_size_KO': 'Error, el nombre no puede tener mas de 40 caracteres',
    //articulo - CodigoA
    'CodigoA_max_size_KO': 'Error, el codigo es demasiado largo. Debe tener 11 caracteres',
    'CodigoA_format_KO': 'Error, el codigo del articulo solo acepta caracteres numericos',
    //articulo - AutoresA
    'AutoresA_min_size_KO': 'Error, el nombre de los autores es demasiado corto. Deberia tener como minimo 5 caracteres',
    'AutoresA_format_KO': 'Error, el formato del nombre solo acepta caracteres alfabeticos con acentos, ñ y ç',
    'AutoresA_max_size_KO': 'Error, el nombre de los autores es demasiado largo. Deberia tener como maximo 200 caracteres',
    //articulo - TituloA
    'TituloA_min_size_KO': 'Error, el titulo es demasiado corto. Deberia tener como minimo 10 caracteres',
    'TituloA_max_size_KO': 'Error, el titulo es demasiado largo. Deberia tener como maximo 100 caracteres',
    'TituloA_format_KO': 'Error, el formato del nombre solo acepta caracteres alfabeticos con acentos, ñ y ç, ademas de , . : y ?',
    //articulo - TituloR
    'TituloR_min_size_KO': 'Error, el titulo de la revista es demasiado corto. Debería tener como minimo 5 caracteres',
    'TituloR_max_size_KO': 'Error, el titulo de la revista es demasiado largo. Debería tener como maximo 100 caracteres',
    'TituloR_format_KO': 'Error, el formato del titulo solo acepta cartacteres alfabeticos, con acentos, ñ y espacios incluidos',
    //articulo - ISSN
    'ISSN_min_size_KO': 'Error, el issn no puede tener menos de 9 caracteres',
    'ISSN_max_size_KO': 'Error, el issn no puede tener mas de 13 caracteres',
    'ISSN_format_KO': 'Error, el issn solo acepta 2 formatos, 1111-111x o bien ISSN1111-111x',
    'ISSN_valor_valido_KO': 'Error, el valor introducido es erroneo. El digito de control no se corresponde con los digitos.',
    //articulo - VolumenR
    'VolumenR_min_size_KO': 'Error, el volumen es demasiado pequeño. No puede ser inferior a 1',
    'VolumenR_max_size_KO': 'Error, el volumen es demasiado grande. No puede superar al 9999',
    'VolumenR_format_KO': 'Error, el volumen solo acepta numericos y alfabeticos',
    //articulo - PagIniA
    'PagIniA_min_size_KO': 'Error, el nº de pagina de inicio es demasiado pequeño.',
    'PagIniA_max_size_KO': 'Error, el nº de pagina de inicio es demasiado grande. No puede tener mas de 4 caracteres',
    'PagIniA_rango_KO': 'Error, la pagina tiene que estar dentro del rango 1 a 1000',
    'PagIniA_format_KO': 'Error, la pagina solo se puede representar mediante numericos',
    //articulo - PagFinA
    'PagFinA_min_size_KO': 'Error, el nº de pagina final es demasiado pequeño.',
    'PagFinA_max_size_KO': 'Error, el nº de pagina final es demasiado grande. No puede tener mas de 4 caracteres',
    'PagFinA_rango_KO': 'Error, el numero de pagina debe estar entre la pagina inicial o 0 y 1000',
    'PagFinA_format_KO': 'Error, la pagina solo se puede representar mediante numericos',
    //articulo - FechaPublicacionR
    'FechaPublicacionR_min_size_KO': 'Error, la fecha es demasiado corta. Debe tener 10 caracteres.',
    'FechaPublicacionR_max_size_KO': 'Error, la fecha es demasiado larga. Debe tener 10 caracteres.',
    'FechaPublicacionR_format_KO': 'Error, la fecha debe contener numeros separados por barras (dd/mm/aaaa)',
    //articulo - FicheropdfA
    'FicheropdfA_max_size_KO': 'Error, el nombre del fichero no puede ser superior a 20 caracteres',
    'FicheropdfA_format_KO': 'Error, el fomato no es valido, solo se pueden meter alfabeticos sin acentos, ni ñ, ni espacios',
    //articulo - nuevo_FicheropdfA
    'nuevo_FicheropdfA_min_file_name_size_KO': 'Error, el nombre del fichero es demasiado corto. No puede ser menor a 7 caracteres.',
    'nuevo_FicheropdfA_max_file_name_size_KO': 'Error, el nombre del fichero es demasiado largo. No puede ser mayor a 20 caracteres.',
    'nuevo_FicheropdfA_not_exist_file_KO': 'Error, si vas a subir un archivo debe haber un fichero subido.',
    'nuevo_FicheropdfA_max_size_file_KO': 'El archivo no puede tener mas de 20MB',
    'nuevo_FicheropdfA_type_file_KO': 'El tipo de archivo no es valido, solo puedes meter pdf',
    'nuevo_FicheropdfA_format_name_file_KO': 'El formato no es valido, solo se aceptan caracteres alfanumericos, sin ñ acentos ni espacios.',
    //articulo - EstadoA
    'EstadoA_vacio_KO': 'Error, el campo no puede quedar vacio',
    'EstadoA_valor_KO': 'Error, solo hay 3 estados posibles: enviado, revision, publicado',
    //ubicacion - id_site
    'id_site_max_size_KO': 'Error, el identificador del sitio es demasiado largo. No puede superar los 11 caracteres',
    'id_site_format_KO': 'Error, el identificador solo acepta caracteres numericos',
    //ubicacion - site_latitud
    'site_latitud_vacio_KO': 'Error, la latitud del sitio no puede ser vacia',
    'site_latitud_formato_rango_KO': 'Error, el formato no es valido. Solo se pueden meter valores enteros o decimales entre -90 y 90',
    'site_latitud_decimales_KO': 'Error, no puede haber + de 6 decimales',
    //ubicacion - site_longitud
    'site_longitud_vacio_KO': 'Error, la longitud del sitio no puede ser vacia',
    'site_longitud_formato_rango_KO': 'Error, el formato no es valido. Solo se pueden meter valores enteros o decimales entre -180 y 180',
    'site_longitud_decimales_KO': 'Error, no puede haber + de 6 decimales',
    //ubicacion - site_altitude
    'site_altitude_vacio_KO': 'Error, la altitud del sitio no puede ser vacia',
    'site_altitude_formato_rango_KO': 'Error, el formato no es valido. Solo se pueden meter valores enteros entre -11000 y 9000',
    //ubicacion - site_locality
    'site_locality_min_size_KO': 'Error, el nombre de la localidad es demasiado corto. Deberia tener mas de 3 caracteres',
    'site_locality_max_size_KO': 'Error, el nombre de la localidad es demasiado largo. No puede tener mas de 40 caracteres',
    'site_locality_format_KO': 'Error, solo se aceptan caracteres alfabeticos (acentos, ñ y ç incluidos) y espacios',
    //ubicacion - site_provider_login
    'site_provider_login_min_size_KO': 'Error, el login es demasiado corto. Deberia tener por lo menos 3 caracteres',
    'site_provider_login_max_size_KO': 'Error, el login es demasiado largo. No puede superar los 30 caracteres',
    'site_provider_login_format_KO': 'Error, el formato no es valido. Solo se pueden insertar caracteres alfanumericos y _',
    //ubicacion - site_north_photo
    'site_north_photo_max_size_KO': 'Error, el nombre del archivo es demasiado largo. Debe tener menos de 50 caracteres',
    'site_north_photo_format_KO': 'Error, el nombre del archivo no es valido. Solo se aceptan alfanumericos, puntos, - o _',
    //ubicacion - nuevo_site_north_photo
    'nuevo_site_north_photo_not_exist_file_KO': 'Error, si vas a subir un archivo debe haber un fichero subido.',
    'nuevo_site_north_photo_max_size_file_KO': 'El archivo no puede tener mas de 20MB',
    'nuevo_site_north_photo_type_file_KO': 'El tipo de archivo no es valido, solo puedes meter jpg',
    'nuevo_site_north_photo_format_name_file_KO': 'El nombre no es valido, solo se aceptan caracteres alfanumericos, sin ñ acentos ni espacios.',
    'nuevo_site_north_photo_min_file_name_size_KO': 'Error, el nombre no puede tener menos de 7 caracteres',
    'nuevo_site_north_photo_max_file_name_size_KO': 'Error, el nombre no puede tener mas de 50 caracteres',
    //ubicacion - site_south_photo
    'site_south_photo_max_size_KO': 'Error, el nombre del archivo es demasiado largo. Debe tener menos de 50 caracteres',
    'site_south_photo_format_KO': 'Error, el nombre del archivo no es valido. Solo se aceptan alfanumericos, puntos, - o _',
    //ubicacion - nuevo_site_south_photo
    'nuevo_site_south_photo_not_exist_file_KO': 'Error, si vas a subir un archivo debe haber un fichero subido.',
    'nuevo_site_south_photo_max_size_file_KO': 'El archivo no puede tener mas de 20MB',
    'nuevo_site_south_photo_type_file_KO': 'El tipo de archivo no es valido, solo puedes meter jpg',
    'nuevo_site_south_photo_format_name_file_KO': 'El nombre no es valido, solo se aceptan caracteres alfanumericos, sin ñ acentos ni espacios.',
    'nuevo_site_south_photo_min_file_name_size_KO': 'Error, el nombre no puede tener menos de 7 caracteres',
    'nuevo_site_south_photo_max_file_name_size_KO': 'Error, el nombre no puede tener mas de 50 caracteres',
    //ubicacion - site_east_photo
    'site_east_photo_max_size_KO': 'Error, el nombre del archivo es demasiado largo. Debe tener menos de 50 caracteres',
    'site_east_photo_format_KO': 'Error, el nombre del archivo no es valido. Solo se aceptan alfanumericos, puntos, - o _',
    //ubicacion - nuevo_site_east_photo
    'nuevo_site_east_photo_not_exist_file_KO': 'Error, si vas a subir un archivo debe haber un fichero subido.',
    'nuevo_site_east_photo_max_size_file_KO': 'El archivo no puede tener mas de 20MB',
    'nuevo_site_east_photo_type_file_KO': 'El tipo de archivo no es valido, solo puedes meter jpg',
    'nuevo_site_east_photo_format_name_file_KO': 'El nombre no es valido, solo se aceptan caracteres alfanumericos, sin ñ acentos ni espacios.',
    'nuevo_site_east_photo_min_file_name_size_KO': 'Error, el nombre no puede tener menos de 7 caracteres',
    'nuevo_site_east_photo_max_file_name_size_KO': 'Error, el nombre no puede tener mas de 50 caracteres',
    //ubicacion - site_west_photo
    'site_west_photo_max_size_KO': 'Error, el nombre del archivo es demasiado largo. Debe tener menos de 50 caracteres',
    'site_west_photo_format_KO': 'Error, el nombre del archivo no es valido. Solo se aceptan alfanumericos, puntos, - o _',
    //ubicacion - nuevo_site_west_photo
    'nuevo_site_west_photo_not_exist_file_KO': 'Error, si vas a subir un archivo debe haber un fichero subido.',
    'nuevo_site_west_photo_max_size_file_KO': 'El archivo no puede tener mas de 20MB',
    'nuevo_site_west_photo_type_file_KO': 'El tipo de archivo no es valido, solo puedes meter jpg',
    'nuevo_site_west_photo_format_name_file_KO': 'El nombre no es valido, solo se aceptan caracteres alfanumericos, sin ñ acentos ni espacios.',
    'nuevo_site_west_photo_min_file_name_size_KO': 'Error, el nombre no puede tener menos de 7 caracteres',
    'nuevo_site_west_photo_max_file_name_size_KO': 'Error, el nombre no puede tener mas de 50 caracteres'
};
