var textos_ES={
    //textos titulos
    'text_titulo_app': 'Interfaz ET2 IU',
    'text_titulo_menu': 'Opciones menu',
    'text_titulo_pie': 'Pie de página',
    'label_seleccioncolumnas': 'Seleccionar columnas',
    //textos tests

    //textos menu
    'text_menu_alumnograduacion': 'Gestionar alumno',
    //alumnograduacion
    'text_titulo_page_alumnograduacion': 'Gestion de datos personales',
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Dar de alta a un alumno',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Editar datos del alumno',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Eliminar datos del alumno',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Mostrar datos del alumno',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Formulario de busqueda',
    //articulo
    'text_titulo_page_articulo': 'Gestion de articulos',
    'text_contenido_titulo_form_articulo_ADD': 'Añadir un nuevo articulo',
    'text_contenido_titulo_form_articulo_EDIT': 'Editar datos de un articulo',
    'text_contenido_titulo_form_articulo_DELETE': 'Eliminar articulo',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Mostrar datos de un articulo',
    'text_contenido_titulo_form_articulo_SEARCH': 'Formulario de busqueda',
    //ubicacion
    'text_titulo_page_ubicacion': 'Gestion de ubicaciones',
    'text_contenido_titulo_form_ubicacion_ADD': 'Añadir nueva ubicacion',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Editar ubicacion',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Eliminar ubicacion',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Mostrar ubicacion',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Formulario de busqueda',
    //atributos
    'alumnograduacion_login': 'Usuario',
    'alumnograduacion_password': 'Contraseña',
    'alumnograduacion_nombre': 'Nombre',
    'alumnograduacion_apellidos': 'Apellidos',
    'alumnograduacion_titulacion': 'Titulacion',
    'alumnograduacion_dni': 'DNI',
    'alumnograduacion_telefono': 'Número de telefono',
    'alumnograduacion_direccion': 'Direccion',
    'alumnograduacion_email': 'Correo electronico',
    'nuevo_alumnograduacion_fotoacto': 'Nueva foto',
    'alumnograduacion_fotoacto': 'Foto',

    'CodigoA': 'Código artículo',
    'AutoresA': 'Nombres autores',
    'TituloA': 'Titulo artículo',
    'TituloR': 'Titulo revista',
    'ISSN': 'ISSN',
    'VolumenR': 'Volumen de la revista',
    'PagIniA': 'Numero página inicial artículo',
    'PagFinA': 'Numero página final artículo',
    'FechaPublicacionR': 'Fecha publicación artículo',
    'FicheropdfA': 'Fichero artículo',
    'nuevo_FicheropdfA': 'Nuevo fichero artículo',
    'EstadoA': 'Estado de tramitación del articulo',

    'id_site': 'Identificador sitio',
    'site_latitud': 'Latitud WGS84',
    'site_longitud': 'Longitud WGS84',
    'site_altitude': 'Altitud sitio',
    'site_locality': 'Localidad del sitio',
    'site_provider_login': 'Login proveedor sitio',
    'site_north_photo': 'Foto hacia el norte',
    'site_south_photo': 'Foto hacia el sur',
    'site_east_photo': 'Foto hacia el este',
    'site_west_photo': 'Foto hacia el oeste',
    'nuevo_site_north_photo': 'Nueva foto hacia el norte',
    'nuevo_site_south_photo': 'Nueva foto hacia el sur',
    'nuevo_site_east_photo': 'Nueva foto hacia el este',
    'nuevo_site_west_photo': 'Nueva foto hacia el oeste',
    //labels
    'label_alumnograduacion_login': 'Usuario',
    'label_alumnograduacion_password': 'Contraseña',
    'label_alumnograduacion_nombre': 'Nombre',
    'label_alumnograduacion_apellidos': 'Apellidos',
    'label_alumnograduacion_titulacion': 'Titulacion',
    'label_alumnograduacion_dni': 'DNI',
    'label_alumnograduacion_telefono': 'Número de telefono',
    'label_alumnograduacion_direccion': 'Direccion',
    'label_alumnograduacion_email': 'Correo electronico',
    'label_nuevo_alumnograduacion_fotoacto': 'Nueva foto',
    'label_alumnograduacion_fotoacto': 'Foto',

    'label_CodigoA': 'Código artículo',
    'label_AutoresA': 'Nombres autores',
    'label_TituloA': 'Titulo artículo',
    'label_TituloR': 'Titulo revista',
    'label_ISSN': 'ISSN',
    'label_VolumenR': 'Volumen de la revista',
    'label_PagIniA': 'Pagina inicial artículo',
    'label_PagFinA': 'Pagina final artículo',
    'label_FechaPublicacionR': 'Fecha publicacion artículo',
    'label_FicheropdfA': 'Fichero articulo',
    'label_nuevo_FicheropdfA': 'Nuevo fichero articulo',
    'label_EstadoA': 'Estado de tramitación del artículo',

    'label_id_site': 'Identificador sitio',
    'label_site_latitud': 'Latitud WGS84',
    'label_site_longitud': 'Longitud WGS84',
    'label_site_altitude': 'Altitud sitio',
    'label_site_locality': 'Localidad del sitio',
    'label_site_provider_login': 'Logon proveedor sitio',
    'label_site_north_photo': 'Foto hacia el norte',
    'label_site_south_photo': 'Foto hacia el sur',
    'label_site_east_photo': 'Foto hacia el este',
    'label_site_west_photo': 'Foto hacia el oeste',
    'label_nuevo_site_north_photo': 'Nueva foto hacia el norte',
    'label_nuevo_site_south_photo': 'Nueva foto hacia el sur',
    'label_nuevo_site_east_photo': 'Nueva foto hacia el este',
    'label_nuevo_site_west_photo': 'Nueva foto hacia el oeste',
    //errores validaciones
    //alumnograduacion_login
    'alumnograduacion_login_min_size_KO': 'El login es demasiado corto, deberia tener entre 4 y 15 caracteres',
    'alumnograduacion_login_max_size_KO': 'El login es demasiado largo, deberia tener entre 4 y 15 caracteres',
    'alumnograduacion_login_format_KO': 'El login solo acepta caracteres alfabeticos sin acentos ni ñ',
    //alumnograduacion_contraseña
    'alumnograduacion_password_min_size_KO': 'La contraseña es demasiado corta, debería tener entre 8 y 64 caracteres',
    'alumnograduacion_password_max_size_KO': 'La contraseña es demasiado larga, debería tener entre 8 y 64 caracteres',
    'alumnograduacion_password_format_KO': 'La contraseña incumple el formato requerido, solo se aceptan caracteres alfabeticos sin acentos, ni ñ, y espacios',
    //alumnograduacion_nombre
    'alumnograduacion_nombre_min_size_KO': 'El nombre es demasiado corto, deberia tener entre 2 y 25 caracteres',
    'alumnograduacion_nombre_max_size_KO': 'El nombre es demasiado largo, deberia tener entre 2 y 25 caracteres',
    'alumnograduacion_nombre_format_KO': 'Error, solo se aceptan caracteres alfabeticos, ñ y acentos incluidos',
    //alumnograduacion_apellidos
    'alumnograduacion_apellidos_min_size_KO': 'Los apellidos son demasiado cortos, debe tener entre 2 y 35 caracteres',
    'alumnograduacion_apellidos_max_size_KO': 'Los apellidos son demasiado largos, debe tener entre 2 y 35 caracteres',
    'alumnograduacion_apellidos_format_KO': 'Error, solo se aceptan caracteres alfabeticos, ñ y acentos incluidos',
    //alumnograduacion_titulacion
    'alumnograduacion_titulacion_format_KO': 'Titulacion invalida. Solo tenemos GREI, GRIA, MEI, MIA o PCEO',
    //alumnograduacion_dni
    'alumnograduacion_dni_min_size_KO': 'El dni/nie es demasiado corto. Debe tener 9 caracteres',
    'alumnograduacion_dni_max_size_KO': 'El dni/nie es demasiado largo. Debe tener 9 caracteres',
    'alumnograduacion_dni_format_KO': 'Error, la cadena introducida no es valida. El formato debe ser 12345678X(para nif) o x1234567x(para nie)',
    'alumnograduacion_dni_format_nif_KO': 'Error, la cadena introducida no es valida, la letra no se corresponde para esa combinacion de numeros',
    'alumnograduacion_dni_format_nie_KO': 'Error, la cadena introducida no es valida, la letra no se corresponde para esa combinacion de numeros',
    //alumnograduacion_telefono
    'alumnograduacion_telefono_min_size_KO': 'Los numeros de telefono no pueden tener menos de 9 caracteres',
    'alumnograduacion_telefono_max_size_KO': 'Los numeros de telefono no pueden tener menos de 9 caracteres',
    'alumnograduacion_format_KO': 'Error, solo se aceptan valores de tipo numerico',
    //alumnograduacion_direccion
    'alumnograduacion_direccion_min_size_KO': 'Error, la direccion es demasiado corta.',
    'alumnograduacion_direccion_max_size_KO': 'Error, la direccion es demasiado larga.',
    'alumnograduacion_direccion_format_KO': 'Error, solo se pueden introducir caracteres alfanuméricos, acentos y ñ incluidos, y espacios. Ademas debe seguir el formato Calle (nombre de la calle), portal, piso, codigo postal, ciudad.',
    //alumnograduacion_email
    'alumnograduacion_email_min_size_KO': 'Error, el email es demasiado corto.',
    'alumnograduacion_email_max_size_KO': 'Error, el email es demasiado largo.',
    'alumnograduacion_email_format_KO': 'El email introducido no cumple el formato valido (usuario@dominio.extension).',
    //alumnograduacion_fotoacto
    'alumnograduacion_fotoacto_max_size_KO': 'El nombre del archivo no puede tener mas de 40 caracteres',
    'alumnograduacion_fotoacto_format_KO': 'El fomato no es valido, solo se pueden meter alfabeticos sin acentos, ni ñ, ni espacios',
    //alumnograduacion_nuevo_fotoacto
    'nuevo_alumnograduacion_fotoacto_not_exist_file_KO': 'Error, si vas a subir una foto debe haber un fichero subido.',
    'nuevo_alumnograduacion_fotoacto_max_size_file_KO': 'El archivo no puede tener mas de 20MB',
    'nuevo_alumnograduacion_fotoacto_type_file_KO': 'El tipo de archivo no es valido, solo puedes meter jpg',
    'nuevo_alumnograduacion_fotoacto_format_name_file_KO': 'El nombre no es valido, solo se aceptan nombres de entre 7 y 100 caracteres, sin ñ acentos ni espacios.',
}