var textos_EN={
    //textos titulos
    'text_titulo_app': 'IU ET2 interface',
    'text_titulo_menu': 'Menu options',
    'text_titulo_pie': 'Footer',
    'label_seleccioncolumnas': 'Select columns',
    //textos tests

    //textos menu
    'text_menu_alumnograduacion': 'Student managment',
    //alumnograduacion
    'text_titulo_page_alumnograduacion': 'Personal data managment',
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Register a student',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Edit student data',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Delete student data',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Show student data',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Search form',
    //articulo
    'text_titulo_page_articulo': 'Article managment',
    'text_contenido_titulo_form_articulo_ADD': 'Add new article',
    'text_contenido_titulo_form_articulo_EDIT': 'Edit article data',
    'text_contenido_titulo_form_articulo_DELETE': 'Delete article',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Show article data',
    'text_contenido_titulo_form_articulo_SEARCH': 'Search form',
    //ubicacion
    'text_titulo_page_ubicacion': 'Location managment',
    'text_contenido_titulo_form_ubicacion_ADD': 'Add new location',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Edit location',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Delete location',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Show location',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Search form',
    //atributos
    'alumnograduacion_login': 'User',
    'alumnograduacion_password': 'Password',
    'alumnograduacion_nombre': 'First name',
    'alumnograduacion_apellidos': 'Surname',
    'alumnograduacion_titulacion': 'Degree',
    'alumnograduacion_dni': 'ID',
    'alumnograduacion_telefono': 'Telephone number',
    'alumnograduacion_direccion': 'Address',
    'alumnograduacion_email': 'Email',
    'nuevo_alumnograduacion_fotoacto': 'New photo',
    'alumnograduacion_fotoacto': 'Photo',

    'CodigoA': 'Article id',
    'AutoresA': 'Author names',
    'TituloA': 'Article name',
    'TituloR': 'Magazine title',
    'ISSN': 'ISSN',
    'VolumenR': 'Magazine volume',
    'PagIniA': 'Article initial page number',
    'PagFinA': 'Article final page number',
    'FechaPublicacionR': 'Article publication date',
    'FicheropdfA': 'Article file',
    'nuevo_FicheropdfA': 'New article file',
    'EstadoA': 'Status of the article',

    'id_site': 'Site id',
    'site_latitud': 'Latitude WGS84',
    'site_longitud': 'Longitude WGS84',
    'site_altitude': 'Altitude',
    'site_locality': 'Site location',
    'site_provider_login': 'Site provider login',
    'site_north_photo': 'Photo towards north',
    'site_south_photo': 'Photo towards south',
    'site_east_photo': 'Photo towards east',
    'site_west_photo': 'Photo towards west',
    'nuevo_site_north_photo': 'New photo towards north',
    'nuevo_site_south_photo': 'New photo towards south',
    'nuevo_site_east_photo': 'New photo towards east',
    'nuevo_site_west_photo': 'New photo towards west',
    //labels
    'label_alumnograduacion_login': 'User',
    'label_alumnograduacion_password': 'Password',
    'label_alumnograduacion_nombre': 'First name',
    'label_alumnograduacion_apellidos': 'Surname',
    'label_alumnograduacion_titulacion': 'Degree',
    'label_alumnograduacion_dni': 'ID',
    'label_alumnograduacion_telefono': 'Telephone number',
    'label_alumnograduacion_direccion': 'Address',
    'label_alumnograduacion_email': 'Email',
    'label_nuevo_alumnograduacion_fotoacto': 'New photo',
    'label_alumnograduacion_fotoacto': 'Photo',

    'label_CodigoA': 'Article id',
    'label_AutoresA': 'Author names',
    'label_TituloA': 'Article name',
    'label_TituloR': 'Magazine title',
    'label_ISSN': 'ISSN',
    'label_VolumenR': 'Magazine volume',
    'label_PagIniA': 'Article initial page number',
    'label_PagFinA': 'Article final page number',
    'label_FechaPublicacionR': 'Article publication date',
    'label_FicheropdfA': 'Article file',
    'label_nuevo_FicheropdfA': 'New article file',
    'label_EstadoA': 'Status of the article',

    'label_id_site': 'Site id',
    'label_site_latitud': 'Latitude WGS84',
    'label_site_longitud': 'Longitude WGS84',
    'label_site_altitude': 'Altitude',
    'label_site_locality': 'Site location',
    'label_site_provider_login': 'Site provider login',
    'label_site_north_photo': 'Photo towards north',
    'label_site_south_photo': 'Photo towards south',
    'label_site_east_photo': 'Photo towards east',
    'label_site_west_photo': 'Photo towards west',
    'label_nuevo_site_north_photo': 'New photo towards north',
    'label_nuevo_site_south_photo': 'New photo towards south',
    'label_nuevo_site_east_photo': 'New photo towards east',
    'label_nuevo_site_west_photo': 'New photo towards west',
    //errores validaciones   
    //alumnograduacion_login
    'alumnograduacion_login_min_size_KO': 'The username is too short, it must be between 4 and 15 characters long',
    'alumnograduacion_login_max_size_KO': 'The user name is too long, it must be between 4 and 15 characters long',
    'alumnograduacion_login_format_KO': 'The username can only contain alphabetic characters, without accents or ñ',
    //alumnograduacion_contraseña
    'alumnograduacion_password_min_size_KO': 'The password is too short, it must be between 8 and 64 characters long',
    'alumnograduacion_password_max_size_KO': 'The password is too long, it must be between 8 and 64 characters long',
    'alumnograduacion_password_format_KO': 'The password does not meet the required format: only alphabetic characters are allowed (no accents, ñ or spaces).',
    //alumnograduacion_nombre
    "alumnograduacion_nombre_min_size_KO": "The name is too short; it should be between 2 and 25 characters long.",
    "alumnograduacion_nombre_max_size_KO": "The name is too long; it should be between 2 and 25 characters long.",
    "alumnograduacion_nombre_format_KO": "Error: only alphabetic characters are allowed (ñ and accents included).",
    //alumnograduacion_apellidos
    "alumnograduacion_apellidos_min_size_KO": "The surname is too short; it must be between 2 and 35 characters long.",
    "alumnograduacion_apellidos_max_size_KO": "The surname is too long; it must be between 2 and 35 characters long.",
    "alumnograduacion_apellidos_format_KO": "Error: only alphabetic characters are allowed (ñ and accents included).",
    //alumnograduacion_titulacion
    "alumnograduacion_titulacion_format_KO": "Invalid degree. Only GREI, GRIA, MEI, MIA or PCEO are allowed.",
    //alumnograduacion_dni
    "alumnograduacion_dni_min_size_KO": "The DNI/NIE is too short. It must have 9 characters.",
    "alumnograduacion_dni_max_size_KO": "The DNI/NIE is too long. It must have 9 characters.",
    "alumnograduacion_dni_format_KO": "Error: the entered value is invalid. The format must be 12345678X (for NIF) or X1234567X (for NIE).",
    "alumnograduacion_dni_format_nif_KO": "Error: the entered value is invalid; the letter does not match the number combination.",
    "alumnograduacion_dni_format_nie_KO": "Error: the entered value is invalid; the letter does not match the number combination.",
    //alumnograduacion_telefono
    "alumnograduacion_telefono_min_size_KO": "Phone numbers cannot have fewer than 9 characters.",
    "alumnograduacion_telefono_max_size_KO": "Phone numbers cannot have fewer than 9 characters.",
    "alumnograduacion_format_KO": "Error: only numeric values are allowed.",
    //alumnograduacion_direccion
    "alumnograduacion_direccion_min_size_KO": "Error: the address is too short.",
    "alumnograduacion_direccion_max_size_KO": "Error: the address is too long.",
    "alumnograduacion_direccion_format_KO": "Error: only alphanumeric characters (including accents and ñ) and spaces are allowed. The format must be: Street (street name), building number, floor, postal code, city.",
    //alumnograduacion_email
    "alumnograduacion_email_min_size_KO": "Error: the email is too short.",
    "alumnograduacion_email_max_size_KO": "Error: the email is too long.",
    "alumnograduacion_email_format_KO": "The entered email does not meet the valid format (user@domain.extension).",
    //alumnograduacion_fotoacto
    "alumnograduacion_fotoacto_max_size_KO": "The file name cannot have more than 40 characters.",
    "alumnograduacion_fotoacto_format_KO": "Invalid format: only alphabetic characters are allowed (no accents, ñ, or spaces).",
    //alumnograduacion_nuevo_fotoacto
    "nuevo_alumnograduacion_fotoacto_not_exist_file_KO": "Error: if you are going to upload a photo, a file must be provided.",
    "nuevo_alumnograduacion_fotoacto_max_size_file_KO": "The file cannot be larger than 20MB.",
    "nuevo_alumnograduacion_fotoacto_type_file_KO": "Invalid file type: only JPG files are allowed.",
    "nuevo_alumnograduacion_fotoacto_format_name_file_KO": "Invalid name: only names between 7 and 100 characters are allowed, without ñ, accents, or spaces."
}