var analysis_preparation_TestSubmit=Array(
    //ADD
    ['analysis_preparation', 'ADD', 1, 'ADD_id_analysis_minimo_OK', {id_analysis_preparation:'',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'id_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'ADD', 2, 'ADD_id_analysis_maximo_OK', {id_analysis_preparation:'1'.repeat(12),name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'id_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'ADD', 3, 'ADD_id_analysis_formato_OK', {id_analysis_preparation:'a',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'id_analysis_preparation_format_KO'],

    ['analysis_preparation', 'ADD', 4, 'ADD_name_analysis_minimo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'abc',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'name_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'ADD', 5, 'ADD_name_analysis_maximo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(101),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'name_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'ADD', 6, 'ADD_name_analysis_formato_OK', {id_analysis_preparation:'1',name_analysis_preparation:'ñaaaaaaaa',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'name_analysis_preparation_format_KO'],

    ['analysis_preparation', 'ADD', 7, 'ADD_description_analysis_minimo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(76),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'description_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'ADD', 8, 'ADD_description_analysis_maximo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(501),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'description_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'ADD', 9, 'ADD_description_analysis_formato_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'1'.repeat(76),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'description_analysis_preparation_format_KO'],

    ['analysis_preparation', 'ADD', 10, 'ADD_bib_analysis_minimo_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a',nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'bib_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'ADD', 11, 'ADD_bib_analysis_maximo_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(202),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'bib_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'ADD', 12, 'ADD_bib_analysis_formato_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a',nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'bib_analysis_preparation_format_KO'],

    ['analysis_preparation', 'ADD', 13, 'ADD_nuevo_file_analysis_preparation_max_size_file_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:20000000,type_file:'application/pdf',format_name_file:'documento.pdf'}}, 'nuevo_file_analysis_preparation_max_sile_size_KO'],
    ['analysis_preparation', 'ADD', 14, 'ADD_nuevo_file_analysis_preparation_type_file_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'image/png',format_name_file:'documento.pdf'}}, 'nuevo_file_analysis_preparation_type_file_KO'],
    ['analysis_preparation', 'ADD', 15, 'ADD_nuevo_file_analysis_preparation_format_name_file_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documeñto.pdf'}}, 'nuevo_file_analysis_preparation_format_name_file_KO'],

    ['analysis_preparation', 'ADD', 16, 'ADD_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}}, true],

    //EDIT
    ['analysis_preparation', 'EDIT', 17, 'EDIT_id_analysis_minimo_OK', {id_analysis_preparation:'',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'id_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'EDIT', 18, 'EDIT_id_analysis_maximo_OK', {id_analysis_preparation:'1'.repeat(12),name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'id_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'EDIT', 19, 'EDIT_id_analysis_formato_OK', {id_analysis_preparation:'a',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'id_analysis_preparation_format_KO'],

    ['analysis_preparation', 'EDIT', 20, 'EDIT_name_analysis_minimo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'abc',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'name_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'EDIT', 21, 'EDIT_name_analysis_maximo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(101),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'name_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'EDIT', 22, 'EDIT_name_analysis_formato_OK', {id_analysis_preparation:'1',name_analysis_preparation:'ñaaaaaaaa',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'name_analysis_preparation_format_KO'],

    ['analysis_preparation', 'EDIT', 23, 'EDIT_description_analysis_minimo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(76),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'description_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'EDIT', 24, 'EDIT_description_analysis_maximo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(501),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'description_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'EDIT', 25, 'EDIT_description_analysis_formato_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'1'.repeat(76),bib_analysis_preparation:'a'.repeat(7), nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'description_analysis_preparation_format_KO'],

    ['analysis_preparation', 'EDIT', 26, 'EDIT_bib_analysis_minimo_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a',nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'bib_analysis_preparation_min_size_KO'],
    ['analysis_preparation', 'EDIT', 27, 'EDIT_bib_analysis_maximo_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(202),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'bib_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'EDIT', 28, 'EDIT_bib_analysis_formato_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a',nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'bib_analysis_preparation_format_KO'],

    ['analysis_preparation', 'EDIT', 29, 'ADD_nuevo_file_analysis_preparation_max_size_file_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:20000000,type_file:'application/pdf',format_name_file:'documento.pdf'}}, 'nuevo_file_analysis_preparation_max_sile_size_KO'],
    ['analysis_preparation', 'EDIT', 30, 'ADD_nuevo_file_analysis_preparation_type_file_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'image/png',format_name_file:'documento.pdf'}}, 'nuevo_file_analysis_preparation_type_file_KO'],
    ['analysis_preparation', 'EDIT', 31, 'ADD_nuevo_file_analysis_preparation_format_name_file_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documeñto.pdf'}}, 'nuevo_file_analysis_preparation_format_name_file_KO'],

    ['analysis_preparation', 'EDIT', 32, 'EDIT_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),nuevo_file_analysis_preparation:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}}, true],

    //SEARCH
    ['analysis_preparation', 'SEARCH', 33, 'SEARCH_id_analysis_maximo_OK', {id_analysis_preparation:'1'.repeat(12),name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), file_analysis_preparation:'fichero.pdf'},'id_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'SEARCH', 34, 'SEARCH_id_analysis_formato_OK', {id_analysis_preparation:'a',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), file_analysis_preparation:'fichero.pdf'},'id_analysis_preparation_format_KO'],

    ['analysis_preparation', 'SEARCH', 35, 'SEARCH_name_analysis_maximo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(101),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), file_analysis_preparation:'fichero.pdf'},'name_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'SEARCH', 36, 'SEARCH_name_analysis_formato_OK', {id_analysis_preparation:'1',name_analysis_preparation:'ñaaaaaaaa',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7), file_analysis_preparation:'fichero.pdf'},'name_analysis_preparation_format_KO'],

    ['analysis_preparation', 'SEARCH', 37, 'SEARCH_description_analysis_maximo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(501),bib_analysis_preparation:'a'.repeat(7), file_analysis_preparation:'fichero.pdf'},'description_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'SEARCH', 38, 'SEARCH_description_analysis_formato_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'1'.repeat(76),bib_analysis_preparation:'a'.repeat(7), file_analysis_preparation:'fichero.pdf'},'description_analysis_preparation_format_KO'],

    ['analysis_preparation', 'SEARCH', 39, 'SEARCH_bib_analysis_maximo_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(202),file_analysis_preparation:'fichero.pdf'},'bib_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'SEARCH', 40, 'SEARCH_bib_analysis_formato_OK', {id_analysis_preparation:'1', name_analysis_preparation:'a'.repeat(8),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a',file_analysis_preparation:'fichero.pdf'},'bib_analysis_preparation_format_KO'],

    ['analysis_preparation', 'SEARCH', 41, 'SEARCH_file_analysis_maximo_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'a'.repeat(102)+'.pdf'}, 'file_analysis_preparation_max_size_KO'],
    ['analysis_preparation', 'SEARCH', 42, 'SEARCH_file_analysis_formato_OK', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'ficheró.pdf'}, 'file_analysis_preparation_format_KO'],

    ['analysis_preparation', 'SEARCH', 43, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 44, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'',description_analysis_preparation:'',bib_analysis_preparation:'',file_analysis_preparation:''}, true],

    ['analysis_preparation', 'SEARCH', 45, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 46, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 47, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'',bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 48, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'',file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 49, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:''}, true],

    ['analysis_preparation', 'SEARCH', 50, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 51, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a',bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 52, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a',file_analysis_preparation:'fichero.pdf'}, true],
    ['analysis_preparation', 'SEARCH', 53, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:'f'}, true],

    ['analysis_preparation', 'SEARCH', 54, 'SEARCH_correcto', {id_analysis_preparation:'1',name_analysis_preparation:'',description_analysis_preparation:'',bib_analysis_preparation:'',file_analysis_preparation:''}, true],
    ['analysis_preparation', 'SEARCH', 55, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'a',description_analysis_preparation:'',bib_analysis_preparation:'',file_analysis_preparation:''}, true],
    ['analysis_preparation', 'SEARCH', 56, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'',description_analysis_preparation:'a',bib_analysis_preparation:'',file_analysis_preparation:''}, true],
    ['analysis_preparation', 'SEARCH', 57, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'',description_analysis_preparation:'',bib_analysis_preparation:'a',file_analysis_preparation:''}, true],
    ['analysis_preparation', 'SEARCH', 58, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'',description_analysis_preparation:'',bib_analysis_preparation:'',file_analysis_preparation:'f'}, true],

    ['analysis_preparation', 'SEARCH', 59, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'a'.repeat(9),description_analysis_preparation:'',bib_analysis_preparation:'',file_analysis_preparation:''}, true],
    ['analysis_preparation', 'SEARCH', 60, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'',description_analysis_preparation:'a'.repeat(81),bib_analysis_preparation:'',file_analysis_preparation:''}, true],
    ['analysis_preparation', 'SEARCH', 61, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'',description_analysis_preparation:'',bib_analysis_preparation:'a'.repeat(7),file_analysis_preparation:''}, true],
    ['analysis_preparation', 'SEARCH', 62, 'SEARCH_correcto', {id_analysis_preparation:'',name_analysis_preparation:'',description_analysis_preparation:'',bib_analysis_preparation:'',file_analysis_preparation:'fichero.pdf'}, true],
);