var characteristic_TestSubmit=Array(
    //ADD
    ['characteristic','ADD',1,'ADD_id_characteristic_minimo_OK',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},'id_characteristic_min_size_KO'],
    ['characteristic','ADD',2,'ADD_id_characteristic_maximo_OK',{id_characteristic:'1'.repeat(15),name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'id_characteristic_max_size_KO'],
    ['characteristic','ADD',3,'ADD_id_characteristic_formato_OK',{id_characteristic:'abc',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'id_characteristic_format_KO'],

    ['characteristic','ADD',4,'ADD_name_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'a',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'name_characteristic_min_size_KO'],
    ['characteristic','ADD',5,'ADD_name_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'name_characteristic_max_size_KO'],
    ['characteristic','ADD',6,'ADD_name_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'character1stíc',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'name_characteristic_format_KO'],

    ['characteristic','ADD',7,'ADD_description_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'description_characteristic_min_size_KO'],
    ['characteristic','ADD',8,'ADD_description_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(5001),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'description_characteristic_max_size_KO'],
    ['characteristic','ADD',9,'ADD_description_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'1'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'description_characteristic_format_KO'],

    ['characteristic','ADD',10,'ADD_data_type_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_min_size_KO'],
    ['characteristic','ADD',11,'ADD_data_type_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'a'.repeat(10),category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_max_size_KO'],
    ['characteristic','ADD',12,'ADD_data_type_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'123456',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_format_KO'],
    ['characteristic','ADD',13,'ADD_data_type_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'texto',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_valor_permitido_KO'],

    ['characteristic','ADD',14,'ADD_category_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_min_size_KO'],
    ['characteristic','ADD',15,'ADD_category_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s'.repeat(10),bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_max_size_KO'],
    ['characteristic','ADD',16,'ADD_category_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soilSite',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_format_KO'],
    ['characteristic','ADD',17,'ADD_category_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'catttttt',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_valor_permitido_KO'],

    ['characteristic','ADD',18,'ADD_bibref_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'bibref_characteristic_min_size_KO'],
    ['characteristic','ADD',19,'ADD_bibref_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R'.repeat(201),nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'bibref_characteristic_max_size_KO'],
    ['characteristic','ADD',20,'ADD_bibref_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfic4',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'bibref_characteristic_format_KO'],

    ['characteristic','ADD',21,'ADD_nuevo_file_characteristic_max_size_file_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:20000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'nuevo_file_characteristic_max_size_file_KO'],
    ['characteristic','ADD',22,'ADD_nuevo_file_characteristic_type_file_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'image/png',format_name_file:'documento.pdf'},},'nuevo_file_characteristic_type_file_KO'],
    ['characteristic','ADD',23,'ADD_nuevo_file_characteristic_format_name_file_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documeñto.pdf'},},'nuevo_file_characteristic_format_name_file_KO'],

    ['characteristic','ADD',24,'ADD_dos_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO']],
    ['characteristic','ADD',25,'ADD_tres_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO']],
    ['characteristic','ADD',26,'ADD_cuatro_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO']],
    ['characteristic','ADD',27,'ADD_cinco_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO','category_characteristic_min_size_KO']],
    ['characteristic','ADD',28,'ADD_seis_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'s',bibref_characteristic:'R',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO','category_characteristic_min_size_KO','bibref_characteristic_min_size_KO']],
    ['characteristic','ADD',29,'ADD_siete_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'s',bibref_characteristic:'R',nuevo_file_characteristic:{max_size_file:2000000,type_file:'image/png',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO','category_characteristic_min_size_KO','bibref_characteristic_min_size_KO','nuevo_file_characteristic_type_file_KO']],

    ['characteristic','ADD',30,'ADD_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},true],

    //EDIT
    ['characteristic','EDIT',31,'EDIT_id_characteristic_minimo_OK',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'id_characteristic_min_size_KO'],
    ['characteristic','EDIT',32,'EDIT_id_characteristic_maximo_OK',{id_characteristic:'1'.repeat(15),name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'id_characteristic_max_size_KO'],
    ['characteristic','EDIT',33,'EDIT_id_characteristic_formato_OK',{id_characteristic:'abc',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'id_characteristic_format_KO'],

    ['characteristic','EDIT',34,'EDIT_name_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'a',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'name_characteristic_min_size_KO'],
    ['characteristic','EDIT',35,'EDIT_name_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'name_characteristic_max_size_KO'],
    ['characteristic','EDIT',36,'EDIT_name_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'character1stíc',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'name_characteristic_format_KO'],

    ['characteristic','EDIT',37,'EDIT_description_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'description_characteristic_min_size_KO'],
    ['characteristic','EDIT',38,'EDIT_description_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(5001),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'description_characteristic_max_size_KO'],
    ['characteristic','EDIT',39,'EDIT_description_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'1'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'description_characteristic_format_KO'],

    ['characteristic','EDIT',40,'EDIT_data_type_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_min_size_KO'],
    ['characteristic','EDIT',41,'EDIT_data_type_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'a'.repeat(8),category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_max_size_KO'],
    ['characteristic','EDIT',42,'EDIT_data_type_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'123456',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_format_KO'],
    ['characteristic','EDIT',43,'EDIT_data_type_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'texto',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'data_type_characteristic_valor_permitido_KO'],

    ['characteristic','EDIT',44,'EDIT_category_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_min_size_KO'],
    ['characteristic','EDIT',45,'EDIT_category_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s'.repeat(10),bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_max_size_KO'],
    ['characteristic','EDIT',46,'EDIT_category_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soilSite',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_format_KO'],
    ['characteristic','EDIT',47,'EDIT_category_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'catttttt',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'category_characteristic_valor_permitido_KO'],

    ['characteristic','EDIT',48,'EDIT_bibref_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'bibref_characteristic_min_size_KO'],
    ['characteristic','EDIT',49,'EDIT_bibref_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R'.repeat(201),nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'bibref_characteristic_max_size_KO'],
    ['characteristic','EDIT',50,'EDIT_bibref_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfic4',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'bibref_characteristic_format_KO'],

    ['characteristic','EDIT',51,'EDIT_nuevo_file_characteristic_max_size_file_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:20000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},'nuevo_file_characteristic_max_size_file_KO'],
    ['characteristic','EDIT',52,'EDIT_nuevo_file_characteristic_type_file_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'image/png',format_name_file:'documento.pdf'},},'nuevo_file_characteristic_type_file_KO'],
    ['characteristic','EDIT',53,'EDIT_nuevo_file_characteristic_format_name_file_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documeñto.pdf'},},'nuevo_file_characteristic_format_name_file_KO'],

    ['characteristic','EDIT',54,'EDIT_dos_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO']],
    ['characteristic','EDIT',55,'EDIT_tres_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO']],
    ['characteristic','EDIT',56,'EDIT_cuatro_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO']],
    ['characteristic','EDIT',57,'EDIT_cinco_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO','category_characteristic_min_size_KO']],
    ['characteristic','EDIT',58,'EDIT_seis_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'s',bibref_characteristic:'R',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO','category_characteristic_min_size_KO','bibref_characteristic_min_size_KO']],
    ['characteristic','EDIT',59,'EDIT_siete_fallos',{id_characteristic:'',name_characteristic:'a',description_characteristic:'a',data_type_characteristic:'t',category_characteristic:'s',bibref_characteristic:'R',nuevo_file_characteristic:{max_size_file:2000000,type_file:'image/png',format_name_file:'documento.pdf'}},['id_characteristic_min_size_KO','name_characteristic_min_size_KO','description_characteristic_min_size_KO','data_type_characteristic_min_size_KO','category_characteristic_min_size_KO','bibref_characteristic_min_size_KO','nuevo_file_characteristic_type_file_KO']],

    ['characteristic','EDIT',60,'EDIT_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{max_size_file:2000000,type_file:'application/pdf',format_name_file:'documento.pdf'},},true],

    //SEARCH
    ['characteristic','SEARCH',61,'SEARCH_id_characteristic_maximo_OK',{id_characteristic:'1'.repeat(15),name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'id_characteristic_max_size_KO'],
    ['characteristic','SEARCH',62,'SEARCH_id_characteristic_formato_OK',{id_characteristic:'abc',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'id_characteristic_format_KO'],

    ['characteristic','SEARCH',63,'SEARCH_name_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'name_characteristic_max_size_KO'],
    ['characteristic','SEARCH',64,'SEARCH_name_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'character1stíc',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'name_characteristic_format_KO'],

    ['characteristic','SEARCH',65,'SEARCH_description_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(5001),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'description_characteristic_max_size_KO'],
    ['characteristic','SEARCH',66,'SEARCH_description_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'1'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'description_characteristic_format_KO'],

    ['characteristic','SEARCH',67,'SEARCH_data_type_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'a'.repeat(8),category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'data_type_characteristic_max_size_KO'],
    ['characteristic','SEARCH',68,'SEARCH_data_type_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'123456',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'data_type_characteristic_format_KO'],
    ['characteristic','SEARCH',69, 'SEARCH_data_type_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'texto',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'data_type_characteristic_valor_permitido_KO'],

    ['characteristic','SEARCH',70,'SEARCH_category_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s'.repeat(10),bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'category_characteristic_max_size_KO'],
    ['characteristic','SEARCH',71,'SEARCH_category_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_sit1',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'category_characteristic_format_KO'],
    ['characteristic','SEARCH',72,'SEARCH_category_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'catttttt',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'category_characteristic_valor_permitido_KO'],

    ['characteristic','SEARCH',73,'SEARCH_bibref_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R'.repeat(201),file_characteristic:'fichero.pdf'},'bibref_characteristic_max_size_KO'],
    ['characteristic','SEARCH',74,'SEARCH_bibref_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfic4',file_characteristic:'fichero.pdf'},'bibref_characteristic_format_KO'],

    ['characteristic','SEARCH',75,'SEARCH_file_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'a'.repeat(100)+'.pdf'},'file_characteristic_max_size_KO'],
    ['characteristic','SEARCH',76,'SEARCH_file_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'ficheró.pdf'},'file_characteristic_format_KO'],

    ['characteristic','SEARCH',77,'SEARCH_dos_fallos',{id_characteristic:'1'.repeat(15),name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},['id_characteristic_max_size_KO','name_characteristic_max_size_KO']],
    ['characteristic','SEARCH',78,'SEARCH_tres_fallos',{id_characteristic:'1'.repeat(15),name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(5001),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},['id_characteristic_max_size_KO','name_characteristic_max_size_KO','description_characteristic_max_size_KO']],
    ['characteristic','SEARCH',79,'SEARCH_cuatro_fallos',{id_characteristic:'1'.repeat(15),name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(5001),data_type_characteristic:'numberr',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},['id_characteristic_max_size_KO','name_characteristic_max_size_KO','description_characteristic_max_size_KO','data_type_characteristic_max_size_KO']],
    ['characteristic','SEARCH',80,'SEARCH_cinco_fallos',{id_characteristic:'1'.repeat(15),name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(5001),data_type_characteristic:'numberr',category_characteristic:'s'.repeat(10),bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},['id_characteristic_max_size_KO','name_characteristic_max_size_KO','description_characteristic_max_size_KO','data_type_characteristic_max_size_KO','category_characteristic_max_size_KO']],
    ['characteristic','SEARCH',81,'SEARCH_seis_fallos',{id_characteristic:'1'.repeat(15),name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(5001),data_type_characteristic:'numberr',category_characteristic:'s'.repeat(10),bibref_characteristic:'R'.repeat(201),file_characteristic:'fichero.pdf'},['id_characteristic_max_size_KO','name_characteristic_max_size_KO','description_characteristic_max_size_KO','data_type_characteristic_max_size_KO','category_characteristic_max_size_KO','bibref_characteristic_max_size_KO']],
    ['characteristic','SEARCH',82,'SEARCH_siete_fallos',{id_characteristic:'1'.repeat(15),name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(5001),data_type_characteristic:'numberr',category_characteristic:'s'.repeat(10),bibref_characteristic:'R'.repeat(201),file_characteristic:'a'.repeat(100)+'.pdf'},['id_characteristic_max_size_KO','name_characteristic_max_size_KO','description_characteristic_max_size_KO','data_type_characteristic_max_size_KO','category_characteristic_max_size_KO','bibref_characteristic_max_size_KO','file_characteristic_max_size_KO']],

    ['characteristic','SEARCH',83,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',84,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],

    ['characteristic','SEARCH',85,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',86,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',87,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',88,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',89,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',90,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',91,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:''},true],

    ['characteristic','SEARCH',92,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'c',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',93,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',94,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',95,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',96,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',97,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'f'},true],

    ['characteristic','SEARCH',98,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',99,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'c',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',100,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'a',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',101,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'t',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',102,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'s',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',103,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'R',file_characteristic:''},true],
    ['characteristic','SEARCH',104,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:'f'},true],

    ['characteristic','SEARCH',105,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',106,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'a'.repeat(83),data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',107,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'text',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',108,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'soil_site',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',109,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'Referencia bibliográfica',file_characteristic:''},true],
    ['characteristic','SEARCH',110,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:'fichero.pdf'},true],
);