//FALTAN TODAS LAS COMPROBACIONES DE LOS FICHEROS EN ADD Y EDIT
var characteristic_TestSubmit=Array(
    //ADD
    ['characteristic','ADD',1,'ADD_id_characteristic_minimo_OK',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'id_characteristic_min_size_KO'],
    ['characteristic','ADD',2,'ADD_id_characteristic_maximo_OK',{id_characteristic:'1'.repeat(15),name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'id_characteristic_max_size_KO'],
    ['characteristic','ADD',3,'ADD_id_characteristic_formato_OK',{id_characteristic:'abc',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'id_characteristic_format_KO'],

    ['characteristic','ADD',4,'ADD_name_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'a',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'name_characteristic_min_size_KO'],
    ['characteristic','ADD',5,'ADD_name_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'name_characteristic_max_size_KO'],
    ['characteristic','ADD',6,'ADD_name_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'character1stíc',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'name_characteristic_format_KO'],

    ['characteristic','ADD',7,'ADD_description_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'description_characteristic_min_size_KO'],
    ['characteristic','ADD',8,'ADD_description_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(5001),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'description_characteristic_max_size_KO'],
    ['characteristic','ADD',9,'ADD_description_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'1'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'description_characteristic_format_KO'],

    ['characteristic','ADD',10,'ADD_data_type_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_min_size_KO'],
    ['characteristic','ADD',11,'ADD_data_type_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'a'.repeat(8),category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_max_size_KO'],
    ['characteristic','ADD',12,'ADD_data_type_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'123456',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_format_KO'],
    ['characteristic','ADD',13,'ADD_data_type_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'texto',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_valor_permitido_KO'],

    ['characteristic','ADD',14,'ADD_category_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_min_size_KO'],
    ['characteristic','ADD',15,'ADD_category_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s'.repeat(9),bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_max_size_KO'],
    ['characteristic','ADD',16,'ADD_category_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_sit1',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_format_KO'],
    ['characteristic','ADD',17,'ADD_category_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soilSite',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_valor_permitido_KO'],

    ['characteristic','ADD',18,'ADD_bibref_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R',nuevo_file_characteristic:{ },},'bibref_characteristic_min_size_KO'],
    ['characteristic','ADD',19,'ADD_bibref_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R'.repeat(201),nuevo_file_characteristic:{ },},'bibref_characteristic_max_size_KO'],
    ['characteristic','ADD',20,'ADD_bibref_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfic4',nuevo_file_characteristic:{ },},'bibref_characteristic_format_KO'],

    ['characteristic','ADD',21,'add correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],
    ['characteristic','ADD',22,'add correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],
    ['characteristic','ADD',23,'add correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],

    ['characteristic','ADD',24,'ADD_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],

    //EDIT
    ['characteristic','EDIT',25,'EDIT_id_characteristic_minimo_OK',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'id_characteristic_min_size_KO'],
    ['characteristic','EDIT',26,'EDIT_id_characteristic_maximo_OK',{id_characteristic:'1'.repeat(15),name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'id_characteristic_max_size_KO'],
    ['characteristic','EDIT',27,'EDIT_id_characteristic_formato_OK',{id_characteristic:'abc',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'id_characteristic_format_KO'],

    ['characteristic','EDIT',28,'EDIT_name_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'a',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'name_characteristic_min_size_KO'],
    ['characteristic','EDIT',29,'EDIT_name_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'name_characteristic_max_size_KO'],
    ['characteristic','EDIT',30,'EDIT_name_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'character1stíc',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'name_characteristic_format_KO'],

    ['characteristic','EDIT',31,'EDIT_description_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'description_characteristic_min_size_KO'],
    ['characteristic','EDIT',32,'EDIT_description_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(5001),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'description_characteristic_max_size_KO'],
    ['characteristic','EDIT',33,'EDIT_description_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'1'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'description_characteristic_format_KO'],

    ['characteristic','EDIT',34,'EDIT_data_type_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_min_size_KO'],
    ['characteristic','EDIT',35,'EDIT_data_type_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'a'.repeat(8),category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_max_size_KO'],
    ['characteristic','EDIT',36,'EDIT_data_type_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'123456',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_format_KO'],
    ['characteristic','EDIT',37,'EDIT_data_type_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'texto',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'data_type_characteristic_valor_permitido_KO'],

    ['characteristic','EDIT',38,'EDIT_category_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_min_size_KO'],
    ['characteristic','EDIT',39,'EDIT_category_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s'.repeat(9),bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_max_size_KO'],
    ['characteristic','EDIT',40,'EDIT_category_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_sit1',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_format_KO'],
    ['characteristic','EDIT',41,'EDIT_category_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soilSite',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},'category_characteristic_valor_permitido_KO'],

    ['characteristic','EDIT',42,'EDIT_bibref_characteristic_minimo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R',nuevo_file_characteristic:{ },},'bibref_characteristic_min_size_KO'],
    ['characteristic','EDIT',43,'EDIT_bibref_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R'.repeat(201),nuevo_file_characteristic:{ },},'bibref_characteristic_max_size_KO'],
    ['characteristic','EDIT',44,'EDIT_bibref_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfic4',nuevo_file_characteristic:{ },},'bibref_characteristic_format_KO'],

    ['characteristic','EDIT',45,'EDIT correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],
    ['characteristic','EDIT',46,'EDIT correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],
    ['characteristic','EDIT',47,'EDIT correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],

    ['characteristic','EDIT',48,'EDIT_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',nuevo_file_characteristic:{ },},true],

    //SEARCH
    ['characteristic','SEARCH',49,'SEARCH_id_characteristic_maximo_OK',{id_characteristic:'1'.repeat(15),name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'id_characteristic_max_size_KO'],
    ['characteristic','SEARCH',50,'SEARCH_id_characteristic_formato_OK',{id_characteristic:'abc',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'id_characteristic_format_KO'],

    ['characteristic','SEARCH',51,'SEARCH_name_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'a'.repeat(102),description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'name_characteristic_max_size_KO'],
    ['characteristic','SEARCH',52,'SEARCH_name_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'character1stíc',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'name_characteristic_format_KO'],

    ['characteristic','SEARCH',53,'SEARCH_description_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(5001),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'description_characteristic_max_size_KO'],
    ['characteristic','SEARCH',54,'SEARCH_description_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'1'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'description_characteristic_format_KO'],

    ['characteristic','SEARCH',55,'SEARCH_data_type_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'a'.repeat(8),category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'data_type_characteristic_max_size_KO'],
    ['characteristic','SEARCH',56,'SEARCH_data_type_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'123456',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'data_type_characteristic_format_KO'],
    ['characteristic','SEARCH',57,'SEARCH_data_type_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'texto',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'data_type_characteristic_valor_permitido_KO'],

    ['characteristic','SEARCH',58,'SEARCH_category_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s'.repeat(9),bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'category_characteristic_max_size_KO'],
    ['characteristic','SEARCH',59,'SEARCH_category_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_sit1',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'category_characteristic_format_KO'],
    ['characteristic','SEARCH',60,'SEARCH_category_characteristic_valor_valido_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soilSite',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},'category_characteristic_valor_permitido_KO'],

    ['characteristic','SEARCH',61,'SEARCH_bibref_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R'.repeat(201),file_characteristic:'fichero.pdf'},'bibref_characteristic_max_size_KO'],
    ['characteristic','SEARCH',62,'SEARCH_bibref_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfic4',file_characteristic:'fichero.pdf'},'bibref_characteristic_format_KO'],

    ['characteristic','SEARCH',63,'SEARCH_file_characteristic_maximo_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'a'.repeat(100)+'.pdf'},true],
    ['characteristic','SEARCH',64,'SEARCH_file_characteristic_formato_OK',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'ficheró.pdf'},true],

    ['characteristic','SEARCH',65,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',66,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],

    ['characteristic','SEARCH',67,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',68,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',69,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',70,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',71,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',72,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',73,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:''},true],

    ['characteristic','SEARCH',74,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'c',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',75,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a',data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',76,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'t',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',77,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'s',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',78,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'R',file_characteristic:'fichero.pdf'},true],
    ['characteristic','SEARCH',79,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'characteristic',description_characteristic:'a'.repeat(83),data_type_characteristic:'text',category_characteristic:'soil_site',bibref_characteristic:'Referencia bibliográfica',file_characteristic:'f'},true],

    ['characteristic','SEARCH',80,'SEARCH_correcto',{id_characteristic:'1',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',81,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'c',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',82,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'a',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',83,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'t',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',84,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'s',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',85,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'R',file_characteristic:''},true],
    ['characteristic','SEARCH',86,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:'f'},true],

    ['characteristic','SEARCH',87,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'characteristic',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',88,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'a'.repeat(83),data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',89,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'text',category_characteristic:'',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',90,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'soil_site',bibref_characteristic:'',file_characteristic:''},true],
    ['characteristic','SEARCH',91,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'Referencia bibliográfica',file_characteristic:''},true],
    ['characteristic','SEARCH',92,'SEARCH_correcto',{id_characteristic:'',name_characteristic:'',description_characteristic:'',data_type_characteristic:'',category_characteristic:'',bibref_characteristic:'',file_characteristic:'fichero.pdf'},true],
);